#include <stdio.h>
#include "version.h"  // generated by auto-version

int main(void) {
    printf("Version:    %s\n",   VERSION_STRING);
    printf("Full:       %s\n",   VERSION_FULL);
    printf("Info:       %s\n",   VERSION_INFO);
    printf("HEX:        0x%08X\n", VERSION_HEX);
    printf("Git SHA:    %s\n",   GIT_SHORT_SHA);
    printf("Branch:     %s\n",   GIT_BRANCH);
    printf("Build date: %s\n",   BUILD_DATE);
    return 0;
}
