use anyhow::Result;

use crate::VersionInfo;

pub fn render(info: &VersionInfo, _vars: &[String]) -> Result<String> {
    let mut out = String::new();
    out.push_str("/* Auto-generated by auto-version. DO NOT EDIT. */\n");
    out.push_str("#pragma once\n\n");
    out.push_str(&format!("#define VERSION_MAJOR    {}\n", info.major));
    out.push_str(&format!("#define VERSION_MINOR    {}\n", info.minor));
    out.push_str(&format!("#define VERSION_PATCH    {}\n", info.patch));
    out.push_str(&format!("#define VERSION_STRING   \"{}\"\n", info.sem_ver));
    out.push_str(&format!(
        "#define VERSION_FULL     \"{}\"\n",
        info.full_sem_ver
    ));
    out.push_str(&format!(
        "#define VERSION_INFO     \"{}\"\n",
        info.informational_version
    ));
    out.push_str(&format!(
        "#define BUILD_DATE       \"{}\"\n",
        info.build_date
    ));
    if let Some(ref sha) = info.short_sha {
        out.push_str(&format!("#define GIT_SHORT_SHA    \"{}\"\n", sha));
    }
    if let Some(ref sha) = info.sha {
        out.push_str(&format!("#define GIT_SHA          \"{}\"\n", sha));
    }
    if let Some(ref b) = info.branch_name {
        out.push_str(&format!("#define GIT_BRANCH       \"{}\"\n", b));
    }
    if let Some(c) = info.commits_since_tag {
        out.push_str(&format!("#define GIT_COMMITS_SINCE_TAG {}\n", c));
    }

    // HEX version: packed as 0xMMmmPPPP (major:8, minor:8, patch:16)
    let hex = pack_hex(info.major, info.minor, info.patch);
    out.push_str(&format!("#define VERSION_HEX      0x{:08X}\n", hex));

    Ok(out)
}

fn pack_hex(major: u64, minor: u64, patch: u64) -> u64 {
    ((major & 0xFF) << 24) | ((minor & 0xFF) << 16) | (patch & 0xFFFF)
}
