use crate::VersionInfo;
use anyhow::Result;

pub fn render(info: &VersionInfo, _vars: &[String]) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Auto-generated by auto-version. DO NOT EDIT.\n");
    out.push_str(&format!("set(VERSION_MAJOR    {})\n", info.major));
    out.push_str(&format!("set(VERSION_MINOR    {})\n", info.minor));
    out.push_str(&format!("set(VERSION_PATCH    {})\n", info.patch));
    out.push_str(&format!("set(VERSION_STRING   \"{}\")\n", info.sem_ver));
    out.push_str(&format!(
        "set(VERSION_FULL     \"{}\")\n",
        info.full_sem_ver
    ));
    out.push_str(&format!(
        "set(VERSION_INFO     \"{}\")\n",
        info.informational_version
    ));
    out.push_str(&format!("set(BUILD_DATE       \"{}\")\n", info.build_date));
    if let Some(ref sha) = info.short_sha {
        out.push_str(&format!("set(GIT_SHORT_SHA    \"{}\")\n", sha));
    }
    if let Some(ref sha) = info.sha {
        out.push_str(&format!("set(GIT_SHA          \"{}\")\n", sha));
    }
    if let Some(ref b) = info.branch_name {
        out.push_str(&format!("set(GIT_BRANCH       \"{}\")\n", b));
    }
    if let Some(c) = info.commits_since_tag {
        out.push_str(&format!("set(GIT_COMMITS_SINCE_TAG {})\n", c));
    }
    Ok(out)
}
