use anyhow::Result;
use crate::VersionInfo;

pub fn render(info: &VersionInfo) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Auto-generated by auto-version. DO NOT EDIT.\n");
    out.push_str(&format!("VERSION_MAJOR    := {}\n", info.major));
    out.push_str(&format!("VERSION_MINOR    := {}\n", info.minor));
    out.push_str(&format!("VERSION_PATCH    := {}\n", info.patch));
    out.push_str(&format!("VERSION_STRING   := {}\n", info.sem_ver));
    out.push_str(&format!("VERSION_FULL     := {}\n", info.full_sem_ver));
    out.push_str(&format!("BUILD_DATE       := {}\n", info.build_date));
    if let Some(ref sha) = info.short_sha {
        out.push_str(&format!("GIT_SHORT_SHA    := {}\n", sha));
    }
    if let Some(ref b) = info.branch_name {
        out.push_str(&format!("GIT_BRANCH       := {}\n", b));
    }
    Ok(out)
}
